name: hello world

on: [workflow_dispatch]

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Ejecutar script Python
        run: python3 main.py